name: time_since
description: convert DateTime and Unix timestamps into human-readable 'time-ago' strings
version: 1.0.1
repository: https://github.com/jefferyabbott/Time-Since

topics:
- time
- timeago
- date-formatting
- time-format
- time-utils


environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # No dependencies

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
